name: Occlum Docker Build and Push

# This is a manual trigger.
on:
  workflow_dispatch:
    inputs:
      OS:
        description: 'OS name (must choose from <centos, ubuntu18, ubuntu20>)'
        required: true
        default: 'ubuntu20'

jobs:
  generate-ubuntu20-image:
      runs-on: ubuntu-20.04
      if: github.event.inputs.OS == 'ubuntu20'

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Occlum release version
        run: echo "RELEASE_VERSION=$(grep 'Version =' src/pal/include/occlum_version.h | awk '{print $4}')" >> $GITHUB_ENV;

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=104857600

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull container
        run: docker pull occlum/occlum:${{ env.RELEASE_VERSION }}-ubuntu20.04
        shell: bash

      - name: Tag latest
        run: docker tag occlum/occlum:${{ env.RELEASE_VERSION }}-ubuntu20.04 occlum/occlum:latest-ubuntu20.04
        shell: bash

      - name: Push latest
        run: docker push occlum/occlum:latest-ubuntu20.04
        shell: bash